name: remoteloop-bump

# on:
#   push:
#     branches:
#       - master

on: push

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npx lerna version patch -m "chore(release): publish %s" --yes
