name: remoteloop-release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    needs: [version-bump]
    strategy:
      matrix:
        os: [macOS-10.14, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Installing dependencies
        run: npm ci && npm run bootstrap -- --no-ci
      - name: Build + Publish
        run: npm run build -- -- --publish=always
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
