name: release

on: push

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
      - uses: actions/setup-node@v1
      - name: Version bump
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "chore: release %s"
          git push
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, windows-2019, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Installing dependencies
        run: npm ci
      - name: Build + Publish
        run: npm run build -- -- --publish always
